development:
  STRIPE_PUBLISHABLE_KEY: "pk_test_Ddcr7FQbOh3eq4UY7ynDuOp6"
  STRIPE_SECRET_KEY: "sk_test_bs7kVzzrNKCzoYRcdIoc2bqc"
  CLOUDINARY_URL: "cloudinary://716967834119596:PJ2G9EmcZRMZxunS7H2YTTQoldg@annamariapl"
  GOOGLE_API_SERVER_KEY: "AIzaSyCnYGkRoFg2Q-zq5hOl1lKG6YKxfnzNBcY"
  GOOGLE_API_BROWSER_KEY: "zaSyC-VYLhwHGhnPQ-7Zqo2mIc3n7iFu4UK1A"

production:
  STRIPE_PUBLISHABLE_KEY: "pk_test_Ddcr7FQbOh3eq4UY7ynDuOp6"
  STRIPE_SECRET_KEY: "sk_test_bs7kVzzrNKCzoYRcdIoc2bqc"
  CLOUDINARY_URL: "cloudinary://716967834119596:PJ2G9EmcZRMZxunS7H2YTTQoldg@annamariapl"
  GOOGLE_API_SERVER_KEY: "AIzaSyCnYGkRoFg2Q-zq5hOl1lKG6YKxfnzNBcY"
  GOOGLE_BROWSER_KEY: "AIzaSyC-VYLhwHGhnPQ-7Zqo2mIc3n7iFu4UK1A"
